# Core
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_ASSERT=y

# Make USB CDC-ACM the console on J20
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_CDC_ACM=y
CONFIG_UART_CONSOLE=y

# Optional niceties
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y

# (Optional but nice to set)
CONFIG_USB_DEVICE_PRODUCT="DWM3001CDK CDC ACM"
CONFIG_USB_DEVICE_VID=0x2FE3
CONFIG_USB_DEVICE_PID=0x0100
